// /app/layout.tsx
import './globals.css';
import { Inter } from 'next/font/google';
import Header from './components/Header';
import PageTransition from './components/PageTransition';
import StairTransition from './components/StairTransition';
import Footer from "@/app/components/Footer";

const jetbrainsMono = Inter({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
    variable: '--font-Inter',
    style: 'normal',
});

export const metadata = {
    title: 'My Next.js App',
    description: 'Generated by Next.js',
};
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="de">
        <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
        </body>
        </html>
    );
}
